services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern

  backend:
    build: ./backend  # Add build context for local build
    container_name: backend
    environment:
      - MONGODB_PATH=mongodb://root:example@mongo-db:27017/
      - SERVER_PORT=9000
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    networks:
      - mern

  frontend:
    build: ./frontend  # Add build context for local build
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mern

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
