apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 9000         # Port exposed to the outside
      targetPort: 9000   # Port on the backend container
